[package]
name = "fhtw_roboter_wettsammeln"
version = "0.1.0"
authors = ["LukasReinhartGraf <if19b019@technikum-wien.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
